geonode_core/layers/urls.py
# -*- coding: utf-8 -*-
# ##############################################################################
#
# Copyright (C) 2016 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ##############################################################################

from geonode import geoserver, qgis_server  # noqa
from geonode.utils import check_ogc_backend
from django.conf.urls import url
from django.views.generic import TemplateView
from geonode.monitoring import register_url_event

from . import views

js_info_dict = {
    'packages': ('geonode.layers',),
}

layers_list = register_url_event()(TemplateView.as_view(template_name='layers/layer_list.html'))

urlpatterns = [
    # 'geonode.layers.views',
    url(r'^$',
        layers_list,
        {'facet_type': 'layers', 'is_layer': True},
        name='layer_browse'),
    url(r'^upload$', views.layer_upload, name='layer_upload'),
    url(r'^upload_metadata$', views.layer_metadata_upload,
        name='layer_metadata_upload'),
    url(r'^upload_style$', views.layer_sld_upload, name='layer_sld_upload'),
    url(r'^load_layer_data$', views.load_layer_data, name='load_layer_data'),
    url(r'^(?P<layername>[^/]*)$', views.layer_detail, name="layer_detail"),
    url(r'^(?P<layername>[^/]*)/metadata$',
        views.layer_metadata, name="layer_metadata"),
    url(r'^(?P<layername>[^/]*)/metadata_advanced$',
        views.layer_metadata_advanced, name="layer_metadata_advanced"),
    url(r'^(?P<layername>[^/]*)/remove$',
        views.layer_remove, name="layer_remove"),
    url(r'^(?P<granule_id>[^/]*)/(?P<layername>[^/]*)/granule_remove$', views.layer_granule_remove,
        name="layer_granule_remove"),
    url(r'^(?P<layername>[^/]*)/replace$',
        views.layer_replace, name="layer_replace"),
    url(r'^(?P<layername>[^/]*)/thumbnail$',
        views.layer_thumbnail, name='layer_thumbnail'),
    url(r'^(?P<layername>[^/]*)/get$', views.get_layer, name='get_layer'),
    url(r'^(?P<layername>[^/]*)/metadata_detail$',
        views.layer_metadata_detail, name='layer_metadata_detail'),
    url(r'^(?P<layername>[^/]*)/metadata_upload$',
        views.layer_metadata_upload, name='layer_metadata_upload'),
    url(r'^(?P<layername>[^/]*)/style_upload$',
        views.layer_sld_upload, name='layer_sld_upload'),
    url(r'^(?P<layername>[^/]*)/style_edit$',
        views.layer_sld_edit, name='layer_sld_edit'),
    url(r'^(?P<layername>[^/]*)/feature_catalogue$',
        views.layer_feature_catalogue, name='layer_feature_catalogue'),
    url(r'^metadata/batch/(?P<ids>[^/]*)/$',
        views.layer_batch_metadata, name='layer_batch_metadata'),
    url(r'^permissions/batch/(?P<ids>[^/]*)/$',
        views.layer_batch_permissions, name='layer_batch_permissions'),
    url(r'^autocomplete/$',
        views.LayerAutocomplete.as_view(), name='autocomplete_layer'),

]

# -- Deprecated url routes for Geoserver authentication -- remove after GeoNode 2.1
# -- Use /gs/acls, gs/resolve_user/, gs/download instead
if check_ogc_backend(geoserver.BACKEND_PACKAGE):
    from geonode.geoserver.views import layer_acls, resolve_user
    urlpatterns = [  # 'geonode.geoserver.views',
        url(r'^acls/?$', layer_acls, name='layer_acls_dep'),
        url(r'^resolve_user/?$', resolve_user,
            name='layer_resolve_user_dep'),
    ] + urlpatterns

geonode_core/layers/forms.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2016 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from geonode.base.forms import ResourceBaseForm
import os
import tempfile
import zipfile

from django import forms

from geonode import geoserver, qgis_server
from geonode.utils import check_ogc_backend

import json
from geonode.utils import unzip_file
from geonode.layers.models import Layer, Attribute


class JSONField(forms.CharField):

    def clean(self, text):
        text = super(JSONField, self).clean(text)
        try:
            return json.loads(text)
        except ValueError:
            raise forms.ValidationError("this field must be valid JSON")


class LayerForm(ResourceBaseForm):
    class Meta(ResourceBaseForm.Meta):
        model = Layer
        exclude = ResourceBaseForm.Meta.exclude + (
            'workspace',
            'store',
            'storeType',
            'alternate',
            'default_style',
            'styles',
            'upload_session',
            'remote_service',)
        # widgets = {
        #     'title': forms.TextInput({'placeholder': title_help_text})
        # }

    def __init__(self, *args, **kwargs):
        super(LayerForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            help_text = self.fields[field].help_text
            self.fields[field].help_text = None
            if help_text != '':
                self.fields[field].widget.attrs.update(
                    {
                        'class': 'has-external-popover',
                        'data-content': help_text,
                        'placeholder': help_text,
                        'data-placement': 'right',
                        'data-container': 'body',
                        'data-html': 'true'
                    }
                )


class LayerUploadForm(forms.Form):
    base_file = forms.FileField()
    dbf_file = forms.FileField(required=False)
    shx_file = forms.FileField(required=False)
    prj_file = forms.FileField(required=False)
    xml_file = forms.FileField(required=False)
    if check_ogc_backend(geoserver.BACKEND_PACKAGE):
        sld_file = forms.FileField(required=False)
    if check_ogc_backend(qgis_server.BACKEND_PACKAGE):
        qml_file = forms.FileField(required=False)

    charset = forms.CharField(required=False)
    metadata_uploaded_preserve = forms.BooleanField(required=False)
    metadata_upload_form = forms.BooleanField(required=False)
    style_upload_form = forms.BooleanField(required=False)

    spatial_files = [
        "base_file",
        "dbf_file",
        "shx_file",
        "prj_file"]

    # Adding style file based on the backend
    if check_ogc_backend(geoserver.BACKEND_PACKAGE):
        spatial_files.append('sld_file')
    if check_ogc_backend(qgis_server.BACKEND_PACKAGE):
        spatial_files.append('qml_file')

    spatial_files = tuple(spatial_files)

    def clean(self):
        cleaned = super(LayerUploadForm, self).clean()
        dbf_file = shx_file = prj_file = xml_file = sld_file = None
        base_name = base_ext = None
        if zipfile.is_zipfile(cleaned["base_file"]):
            filenames = zipfile.ZipFile(cleaned["base_file"], allowZip64=True).namelist()
            for filename in filenames:
                name, ext = os.path.splitext(filename)
                if ext.lower() == '.shp':
                    if base_name is not None:
                        raise forms.ValidationError(
                            "Only one shapefile per zip is allowed")
                    base_name = name
                    base_ext = ext
                elif ext.lower() == '.dbf':
                    dbf_file = filename
                elif ext.lower() == '.shx':
                    shx_file = filename
                elif ext.lower() == '.prj':
                    prj_file = filename
                elif ext.lower() == '.xml':
                    xml_file = filename
                elif ext.lower() == '.sld':
                    sld_file = filename
            if base_name is None:
                raise forms.ValidationError(
                    "Zip files can only contain shapefile.")
        else:
            base_name, base_ext = os.path.splitext(cleaned["base_file"].name)
            if cleaned["dbf_file"] is not None:
                dbf_file = cleaned["dbf_file"].name
            if cleaned["shx_file"] is not None:
                shx_file = cleaned["shx_file"].name
            if cleaned["prj_file"] is not None:
                prj_file = cleaned["prj_file"].name
            if cleaned["xml_file"] is not None:
                xml_file = cleaned["xml_file"].name
            # SLD style only available in GeoServer backend
            if check_ogc_backend(geoserver.BACKEND_PACKAGE):
                if cleaned["sld_file"] is not None:
                    sld_file = cleaned["sld_file"].name

        if not cleaned["metadata_upload_form"] and not cleaned["style_upload_form"] and base_ext.lower() not in (
                ".shp", ".tif", ".tiff", ".geotif", ".geotiff", ".asc", ".sld", ".kml", ".kmz"):
            raise forms.ValidationError(
                "Only Shapefiles, GeoTiffs, and ASCIIs are supported. You "
                "uploaded a %s file" % base_ext)
        elif cleaned["metadata_upload_form"] and base_ext.lower() not in (".xml"):
            raise forms.ValidationError(
                "Only XML files are supported. You uploaded a %s file" %
                base_ext)
        elif cleaned["style_upload_form"] and base_ext.lower() not in (".sld"):
            raise forms.ValidationError(
                "Only SLD files are supported. You uploaded a %s file" %
                base_ext)

        if base_ext.lower() == ".shp":
            if dbf_file is None or shx_file is None:
                raise forms.ValidationError(
                    "When uploading Shapefiles, .shx and .dbf files are also required.")
            dbf_name, __ = os.path.splitext(dbf_file)
            shx_name, __ = os.path.splitext(shx_file)
            if dbf_name != base_name or shx_name != base_name:
                raise forms.ValidationError(
                    "It looks like you're uploading "
                    "components from different Shapefiles. Please "
                    "double-check your file selections.")
            if prj_file is not None:
                if os.path.splitext(prj_file)[0] != base_name:
                    raise forms.ValidationError(
                        "It looks like you're "
                        "uploading components from different Shapefiles. "
                        "Please double-check your file selections.")
            if xml_file is not None:
                if os.path.splitext(xml_file)[0] != base_name:
                    if xml_file.find('.shp') != -1:
                        # force rename of file so that file.shp.xml doesn't
                        # overwrite as file.shp
                        if cleaned.get("xml_file"):
                            cleaned["xml_file"].name = '%s.xml' % base_name
            if sld_file is not None:
                if os.path.splitext(sld_file)[0] != base_name:
                    if sld_file.find('.shp') != -1:
                        # force rename of file so that file.shp.xml doesn't
                        # overwrite as file.shp
                        if cleaned.get("sld_file"):
                            cleaned["sld_file"].name = '%s.sld' % base_name
        return cleaned

    def write_files(self):
        absolute_base_file = None
        tempdir = tempfile.mkdtemp()
        if zipfile.is_zipfile(self.cleaned_data['base_file']):
            absolute_base_file = unzip_file(self.cleaned_data['base_file'],
                                            '.shp', tempdir=tempdir)
        else:
            for field in self.spatial_files:
                f = self.cleaned_data[field]
                if f is not None:
                    path = os.path.join(tempdir, f.name)
                    with open(path, 'wb') as writable:
                        for c in f.chunks():
                            writable.write(c)
            absolute_base_file = os.path.join(tempdir,
                                              self.cleaned_data["base_file"].name)
        return tempdir, absolute_base_file


class NewLayerUploadForm(LayerUploadForm):
    if check_ogc_backend(geoserver.BACKEND_PACKAGE):
        sld_file = forms.FileField(required=False)
    if check_ogc_backend(qgis_server.BACKEND_PACKAGE):
        qml_file = forms.FileField(required=False)
    xml_file = forms.FileField(required=False)

    abstract = forms.CharField(required=False)
    layer_title = forms.CharField(required=False)
    permissions = JSONField()
    charset = forms.CharField(required=False)
    metadata_uploaded_preserve = forms.BooleanField(required=False)

    spatial_files = [
        "base_file",
        "dbf_file",
        "shx_file",
        "prj_file",
        "xml_file"
    ]
    # Adding style file based on the backend
    if check_ogc_backend(geoserver.BACKEND_PACKAGE):
        spatial_files.append('sld_file')
    if check_ogc_backend(qgis_server.BACKEND_PACKAGE):
        spatial_files.append('qml_file')

geonode_core/layers/templates/upload/layer_upload.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %} {% trans "Upload Layer"  %} - {{ block.super }}  {% endblock %}

{% block body_class %}{% trans "layers upload" %}{% endblock %}


{% block head %}

{{ block.super }}
{% endblock %}

{% block body_outer %}
<div class="page-header">
  <a href="{% url "layer_browse" %}?limit={{ CLIENT_RESULTS_LIMIT }}" class="btn btn-primary pull-right">{% trans "Explore Layers" %}</a>
  <h2 class="page-title">{% trans "Upload Layers" %}</h2>

  <script language="javascript">
    var json_mosaics = [
          {% for mosaic in mosaics %}
            {
                "name" : "{{mosaic.name}}",
                "workspace" : "{{mosaic.workspace}}",
                "is_mosaic" : "{{mosaic.is_mosaic}}",
                "has_time" : "{{mosaic.has_time}}",
                "has_elevation" : "{{mosaic.has_elevation}}",
                "time_regex" : "{{mosaic.time_regex}}",
                "elevation_regex" : "{{mosaic.elevation_regex}}"
            },
          {% endfor %}
    ]
  </script>
</div>
<div class="row">
  <div class="col-md-8">
    {% if incomplete %}
    <section class="widget" id="incomplete-download-list">
      <h3>{% trans "Incomplete Uploads" %}</h3>
      <p>{% trans "You have the following incomplete uploads" %}:</p>
      {% for u in incomplete %}
      <div class="clearfix uip" id="incomplete-{{ u.import_id }}">
        <div class="pull-left">{{ u.name }}, {% trans "last updated on" %} {{ u.date }}</div>
        <div class="upload_actions pull-right">
          <a class="btn btn-mini" href="#" id="resume-{{ u.import_id }}">{% trans "Resume" %}</a>
          <a class="btn btn-mini" href="#" id="delete-{{ u.import_id }}"><i class="icon-trash"></i> {% trans "Delete" %}</a>
        </div>
      </div>
      {% endfor %}
    </section>
    <div id="confirm-delete" class="hidden alert alert-warning">
      {% trans "Are you sure you want to delete this upload?" %}
      <a href="#y" class="btn btn-danger">{% trans "Delete" %}</a>
      <a href="#n" class="btn btn-default">{% trans "Cancel" %}</a>
      <a href="#yy">{% trans "Delete, and don't ask me again." %}</a>
    </div>
    {% endif %}

    {% block additional_info %}{% endblock %}

    {% if errors %}
    <div id="errors" class="alert alert-danger">
      {% for error in errors %}
      <p>{{ error }}</p>
      {% endfor %}
    </div>
    {% endif %}

    <div id="upload-status"></div>

    <section id="drop-zone">
      <h3><i class="fa fa-cloud-upload"></i><br />{% trans "Drop files here" %}</h3>
    </section>

    <p>{% trans " or select them one by one:" %}</p>

    <form id="file-uploader" method="post" enctype="multipart/form-data">
      <!-- UI change to hide the list of previously uploaded files from the user -->
      <input type="file" id="file-input" style="display: none;" multiple>
      <input class="btn btn-default" type="button" value="{% trans "Choose Files" %}" onclick="document.getElementById('file-input').click();">
    </form>

    <section class="widget">
      <ul id="global-errors"></ul>
      <h4>{% trans "Files to be uploaded" %}</h4>
      <div id="file-queue"></div>
      <div class="checkbox" style="display:none;" id="metadata_uploaded_preserve_check">
          {% trans "Preserve Metadata XML" %} <input type="checkbox" name="metadata_uploaded_preserve" id="id_metadata_uploaded_preserve"/>
      </div>
    </section>

    <section class="charset">
      <p>{% trans "Select the charset or leave default" %}</p>
      <select id="charset">
        {% for charset in charsets %}
        {% if charset.0 == 'UTF-8' %}
        <option selected='selected' value={{ charset.0 }}>{{ charset.1 }}</option>
        {% else %}
        <option value={{ charset.0 }}>{{ charset.1 }}</option>
        {% endif %}
        {% endfor %}
      </select>
    </section>

    <section>
      <a href="{% url "layer_upload" %}" id="clear-button" class="btn btn-default">{% trans "Clear" %}</a>
      <a href="#" id="upload-button" class="btn btn-danger">{% trans "Upload files" %}</a>
    </section>
  </div>

  {% if GEONODE_SECURITY_ENABLED %}
  <div class="col-md-4">
    <h3>{% trans "Permissions"  %}</h3>
    <form id="permission_form">
      {% include "_permissions.html" %}
    </form>
  </div>
  {% endif %}
</div>
{% endblock %}


{% block extra_script %}
{{ block.super }}
<script data-main="{% static 'geonode/js/upload/main.js' %}"
  src="{% static 'lib/js/require.js' %}">
</script>
<script type="text/javascript">
{% autoescape off %}

  csrf_token =  "{{ csrf_token }}",
  form_target = "{{ UPLOADER_URL }}",
  time_enabled = {{ TIME_ENABLED|lower  }},
  mosaic_enabled = {{ MOSAIC_ENABLED|lower  }},
  userLookup = "{% url "account_ajax_lookup" %}"

{% endautoescape %}

</script>
{% if GEONODE_SECURITY_ENABLED %}
{% with resource=layer %}
{% include "_permissions_form_js.html" %}
{% endwith %}
{% endif %}
{% endblock extra_script %}

geonode_core/layers/templates/upload/layer_upload_base.html
{% extends "geonode_base.html" %}
{% load i18n %}

{% block head %}
{{ block.super }}
<style>
    #left {
        float: left;
        margin: 5px 0 0 10px;
        /* height: 40px; */
    }

    #right {
        float: right;
        margin: 5px 10px 0 0;
        /* height: 40px; */
    }

    .inline-headers h4, .inline-headers select {
      display: inline-block;
      vertical-align: top;
    }

    .active {
        background-color: #cccccc !important;
        font-weight: bold !important;
    }

    .faqHeader {
        font-size: 17px;
        margin: 20px;
    }

    .panel-heading [data-toggle="collapse"]:after {
        font-family: 'FontAwesome';
        content: "\f078"; /* "play" icon */
        float: right;
        color: #F58723;
        font-size: 18px;
        line-height: 22px;
        /* rotate "play" icon from > (right arrow) to down arrow */
    /*    -webkit-transform: rotate(-90deg);
        -moz-transform: rotate(-90deg);
        -ms-transform: rotate(-90deg);
        -o-transform: rotate(-90deg);
        transform: rotate(-90deg); */
    }

    .panel-heading [data-toggle="collapse"].collapsed:after {
        /* rotate "play" icon from > (right arrow) to ^ (up arrow) */
    /*    -webkit-transform: rotate(90deg);
        -moz-transform: rotate(90deg);
        -ms-transform: rotate(90deg);
        -o-transform: rotate(90deg);
        transform: rotate(90deg); */
        color: #454444;
    }

    .help-tip{
        position: absolute;
        /* top: 18px;
        right: 18px;
        bottom: 50px;  */
        margin-left: 10px;
        text-align: center;
        background-color: #BCDBEA;
        border-radius: 50%;
        width: 24px;
        height: 24px;
        font-size: 14px;
        line-height: 26px;
        cursor: default;
    }

    .help-tip:before{
        content:'?';
        font-weight: bold;
        color:#fff;
    }

    .button-tip{
        position: absolute;
    }

    .help-tip:hover p,
    .button-tip:hover p{
        display:block;
        transform-origin: 100% 0%;

        -webkit-animation: fadeIn 0.3s ease-in-out;
        animation: fadeIn 0.3s ease-in-out;
    }

    .help-tip p,
    .button-tip p{    /* The tooltip */
        display: none;
        text-align: justify;
        background-color: #1E2021;
        padding: 10px;
        width: 150px;
        max-width: 300px;
        position: absolute;
        border-radius: 10px;
        box-shadow: 1px 1px 1px rgba(0, 0, 0, 0.2);
        right: -15px;
        color: #FFF;
        font-size: 10px;
        line-height: 1.4;
        z-index: 10000;
    }

    .help-tip p:before,
    .button-tip p:before{ /* The pointer of the tooltip */
        position: absolute;
        content: '';
        width:0;
        height: 0;
        border:6px solid transparent;
        border-bottom-color:#1E2021;
        right:10px;
        top:-12px;
    }

    .help-tip p:after,
    .button-tip p:after{ /* Prevents the tooltip from being hidden */
        width:100%;
        height:40px;
        content:'';
        position: absolute;
        top:-40px;
        left:0;
    }

    /* CSS animation */

    @-webkit-keyframes fadeIn {
        0% {
            opacity:0;
            transform: scale(0.6);
        }

        100% {
            opacity:100%;
            transform: scale(1);
        }
    }

    @keyframes fadeIn {
        0% { opacity:0; }
        100% { opacity:100%; }
    }
</style>
{% endblock %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}{% trans "data" %}{% endblock %}

{% block body_outer %}
<div class="page-header">
  <a href="{% url "layer_browse" %}?limit={{ CLIENT_RESULTS_LIMIT }}" class="btn btn-primary pull-right">{% trans "Explore Layers" %}</a>
  <h2 class="page-title">{% trans "Upload Layers" %}</h2>
</div>
<div class="row">
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
</div>
{% endblock body_outer %}

geonode_core/layers/templates/upload/layer_upload_csv.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block body_class %}data data-list upload{% endblock %}

{% block title %} {% trans "Upload Layer Step: CSV Field Mapping" %} - {{ block.super }} {% endblock %}

{% block head %}
{{ block.super }}
{% endblock %}

{% block body %}
<div class="span7">
  <h2> {% trans "Geospatial Data" %} "{{ layer_name }}" </h2>

    {% if present_choices %}
        <p>{% trans "Please indicate which attributes contain the latitude and longitude coordinates in the CSV data." %}</p>
        {% if guessed_lat_or_lng %}
            <p>{% blocktrans %}With this data, GeoNode was able to guess which attributes contain the
                latitude and longitude coordinates, but please confirm that the correct
                attributes are selected below.{% endblocktrans %}</p>
        {% endif %}

        <form method="POST" id="csvForm" role="form">
          {% csrf_token %}
          {% if error %}
          <div class="msg alert alert-error">{{ error }}</div>
          {% endif %}
          <div>
            <label for="lat" style="display: inline-block; width: 75px">{% trans "Latitude" %}</label>
            <select id="lat" name="lat">
              <option value="None">{% trans "Select an attribute" %}</option>
              {% for option in point_candidates %}
              <option value="{{ option }}"
              {% if selected_lat and selected_lat == option %}
              selected="selected"
              {% endif %}
              >{{ option }}</option>
              {% endfor %}
            </select>
          </div>
          <div style="margin: 10px 0">
            <label for="lat" style="display: inline-block; width: 75px">{% trans "Longitude" %}</label>
            <select id="lng" name="lng">
              <option value="None">{% trans "Select an attribute" %}</option>
              {% for option in point_candidates %}
              <option value="{{ option }}"
              {% if selected_lng and selected_lng == option %}
              selected="selected"
              {% endif %}
              >{{ option }}</option>
              {% endfor %}
            </select>
          </div>

          <a href="{% url "layer_upload" %}" class="btn btn-primary pull-left">{% trans "Cancel" %}</a> &nbsp;
          <button id='next' class="btn btn-default" type="submit" value="{% trans 'Next' %}"> Next
              <i id="next-spinner" class="fa fa-spinner fa-spin hide"></i>
          </button>
          <div id="upload-status"></div>
        </form>

        <div id="csv-status">
            <div id="status">
            </div>
        </div>

    {% else %}
        <p>{% blocktrans %}We did not detect columns that could be used for the latitude and longitude.
        Please verify that you have two columns in your csv file that can be used for
        the latitude and longitude.{% endblocktrans %}</p>
    {% endif %}
</div>
{% endblock %}

{% block extra_script %}
{{ block.super }}
<script data-main="{% static 'geonode/js/upload/csv.js' %}"
  src="{% static 'lib/js/require.js' %}">
</script>
<script type="text/javascript">
{% autoescape off %}
{% if async_upload %}
//enableUploadProgress('timeForm');
{% endif %}
{% endautoescape %}
</script>
{% endblock %}

geonode_core/layers/templates/upload/layer_upload_error.html
{% extends "upload/layer_upload_base.html" %}

{% block body_class %}data data-list upload{% endblock %}

{% block body %}
  <p>{{ error_msg|safe }}</p>
{% endblock %}

geonode_core/layers/templates/upload/layer_upload_invalid.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% block body_class %}data data-list upload{% endblock %}

{% block body %}
<p>{% trans "Your upload is either complete or you haven't resumed an earlier one." %}</p>
<p>{% trans "Return to" %} <a href="{% url "layer_upload" %}">{% trans "Upload Form" %}</a>.</p>
{% endblock %}

geonode_core/layers/templates/upload/layer_upload_metadata_base.html
{% extends "geonode_base.html" %}
{% load i18n %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}{% trans "data" %}{% endblock %}

{% block body_outer %}
<div class="page-header">
  <a href="{% url "layer_browse" %}?limit={{ CLIENT_RESULTS_LIMIT }}" class="btn btn-primary pull-right">{% trans "Explore Layers" %}</a>
  <h2 class="page-title">{% trans "Upload Layer Metadata" %}</h2>
</div>
<div class="row">
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
</div>
{% endblock body_outer %}

geonode_core/layers/templates/upload/no_upload.html
{% extends "upload/base.html" %}
{% load i18n %}

{% block body %}
<div class="twocol">
    <p>{% trans "Your upload is either complete or you haven't resumed an earlier one." %}</p>
    <p>{% blocktrans %}Returning to the upload starting page in <span id="cnt">5</span>seconds {% endblocktrans %}.</p>
    <p>{% blocktrans %} Or just go {% endblocktrans %}<a href="{% url "layer_upload" %}">{% blocktrans %}now{% endblocktrans %}</a>.</p>
</div>
<script type="text/javascript">
    var cnt = 5;
    window.setInterval(function() {
        Ext.get('cnt').dom.innerHTML = cnt--;
        if (cnt == 0) {
            window.location = "{% url "layer_upload" %}";
        }
    }, 1000);
</script>
{% endblock %}